linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *osx
        osx_image: xcode9.4
        env: CONAN_APPLE_CLANG_VERSIONS=9.1
      - <<: *osx
        osx_image: xcode7.3
        env: CONAN_APPLE_CLANG_VERSIONS=7.3

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh || True
  - cat ${CONAN_LOGGING_FILE}
  - file /Users/travis/.conan/data/log4cplus/2.0.0-rc2/bincrafters/stable/package/13b48d56cd5d7dff22684d58482d685be985d688/conanmanifest.txt || True
  - cat -e /Users/travis/.conan/data/log4cplus/2.0.0-rc2/bincrafters/stable/package/13b48d56cd5d7dff22684d58482d685be985d688/conanmanifest.txt || True
